[package]
name = "rust-ws"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
